linters-settings:
  misspell:
    locale: US
    ignore-words:
      - stretchr
      - lipgloss
      - cobra
      - viper
      - goroutines
      - waitgroups
      - stdin
      - stdout
      - stderr
      - gopath
      - godoc
      - esousa97
      - enoque
      - sousa
